name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build packages from flake
        id: build-packages-from-flake
        run: |
          mkdir --parents artifacts
          nix build .#document
          mv result artifacts/document.pdf
      - name: Create release
        uses: release-drafter/release-drafter@v6.1.0
        with:
          publish: true
          tag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v2.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
          files: 'artifacts/**/*.pdf'
          # Do not change the body
          append_body: true
          body: ''
